#!/usr/bin/env python3
# Synthetic-data collection harness for Phase 2 W4.
#
# drives an AirSim multirotor through a scripted waypoint mission, captures
# RGB + depth + segmentation frames, emits YOLO labels via the ground-truth
# instance segmentation masks.
#
# this is a *skeleton*. the hard parts (an AirSim env, the actual mesh-to-
# taxonomy table, segmentation-mask -> bbox conversion) all land in W4.
# what's stable now is the *shape* of the output dataset so merge_datasets.py
# can plan around it.
#
# design notes:
#   - simGetSegmentationObjectID(name) is used to assign a stable colour to
#     every spawned actor matching OBJECT_REGEXES. doing this deterministically
#     at start-of-run reduces the mask->class lookup to a colour LUT.
#   - we emit into data/synthetic/{run_id}/ in the same layout as the other
#     YOLO datasets, so merge_datasets.py consumes it unchanged.
#   - skip frames where the only visible objects are < MIN_BOX_PX after
#     scaling to 640 - they waste capacity and would fail G2 anyway.
#
# usage (with AirSim running):
#   python scripts/airsim_collect.py \
#       --run-id    airsim_run_001 \
#       --n-frames  2000 \
#       --waypoints configs/airsim_waypoints.json \
#       --dst       data/synthetic/airsim_run_001
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

OUR_CLASS_NAMES = [
    "Person", "Vehicle-Wheeled", "Vehicle-Tracked",
    "Aircraft-Rotary", "Aircraft-Fixed", "Watercraft", "Structure-Temp",
]

# AirSim mesh-name regex -> our class id.
# extend this when adding new envs / assets.
OBJECT_REGEXES: list[tuple[re.Pattern[str], int]] = [
    (re.compile(r"(?i)^(BP_)?Mannequin"),                 0),  # Person
    (re.compile(r"(?i)^(BP_)?(Car|SUV|Truck|Pickup)"),    1),  # Vehicle-Wheeled
    (re.compile(r"(?i)^(BP_)?(Tank|APC|IFV|Bulldozer)"),  2),  # Vehicle-Tracked
    (re.compile(r"(?i)^(BP_)?Helicopter"),                3),  # Aircraft-Rotary
    (re.compile(r"(?i)^(BP_)?(Plane|Jet)"),               4),  # Aircraft-Fixed
    (re.compile(r"(?i)^(BP_)?(Boat|Ship|RHIB)"),          5),  # Watercraft
    (re.compile(r"(?i)^(BP_)?(Tent|SandbagWall)"),        6),  # Structure-Temp
]

MIN_BOX_PX = 5


@dataclass
class Waypoint:
    x: float
    y: float
    z: float
    yaw_deg: float
    dwell_s: float = 0.5
    n_frames: int = 5


# ---- glue surface. real AirSim calls deferred to W4. ----
def _connect_airsim():  # pragma: no cover - W4
    import airsim  # type: ignore
    c = airsim.MultirotorClient()
    c.confirmConnection()
    c.enableApiControl(True)
    c.armDisarm(True)
    return c


def _assign_segmentation_ids(client) -> dict[int, int]:  # pragma: no cover - W4
    # walk every actor, match against OBJECT_REGEXES, assign a stable seg id,
    # return {seg_rgb_int: our_class_id} LUT.
    raise NotImplementedError("W4 task")


def _capture_frame(client, lut: dict[int, int]) -> tuple[bytes, list[tuple[int, float, float, float, float]]]:  # pragma: no cover - W4
    # returns (png_bytes, [(cls, cx, cy, w, h) normalised])
    raise NotImplementedError("W4 task")


# ---- testable today: waypoint loader, dataset layout, manifest ----
def load_waypoints(path: Path) -> list[Waypoint]:
    raw = json.loads(path.read_text(encoding="utf-8"))
    out: list[Waypoint] = []
    for w in raw:
        out.append(Waypoint(
            x=float(w["x"]), y=float(w["y"]), z=float(w["z"]),
            yaw_deg=float(w.get("yaw_deg", 0.0)),
            dwell_s=float(w.get("dwell_s", 0.5)),
            n_frames=int(w.get("n_frames", 5)),
        ))
    if not out:
        raise ValueError("waypoint file is empty")
    return out


def prepare_dataset_layout(dst: Path) -> None:
    # synthetic is train-only by convention
    for split in ("train",):
        (dst / "images" / split).mkdir(parents=True, exist_ok=True)
        (dst / "labels" / split).mkdir(parents=True, exist_ok=True)
    if (dst / "data.yaml").exists():
        return
    lines = [
        "# Auto-generated by scripts/airsim_collect.py",
        f"path: {dst.resolve()}",
        "train: images/train",
        "val:   images/train      # synthetic is never used for val",
        "",
        f"nc: {len(OUR_CLASS_NAMES)}",
        "names:",
    ]
    for i, name in enumerate(OUR_CLASS_NAMES):
        lines.append(f"  {i}: {name}")
    (dst / "data.yaml").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--run-id",    required=True)
    ap.add_argument("--n-frames",  type=int, default=1000)
    ap.add_argument("--waypoints", type=Path, required=True)
    ap.add_argument("--dst",       type=Path, required=True)
    ap.add_argument("--dry-run",   action="store_true",
                    help="validate inputs + create layout, don't touch AirSim.")
    args = ap.parse_args()

    waypoints = load_waypoints(args.waypoints)
    prepare_dataset_layout(args.dst)
    print(f"Run {args.run_id}: {len(waypoints)} waypoints, target {args.n_frames} frames -> {args.dst}")

    if args.dry_run:
        print("[dry-run] dataset layout ready; AirSim not contacted.")
        return 0

    try:
        client = _connect_airsim()
        _lut = _assign_segmentation_ids(client)  # noqa: F841 -- consumed by W4 capture loop
    except Exception as e:  # pragma: no cover - W4 hardware
        print(f"AirSim setup failed: {e}", file=sys.stderr)
        return 2

    # capture loop lands in W4
    raise NotImplementedError("AirSim capture loop lands Phase 2 W4")


if __name__ == "__main__":
    sys.exit(main())
