#!/usr/bin/env python3
# DOTA (v1.0 / v1.5 / v2.0) -> YOLO format, mapped onto our 7-class taxonomy
# (docs/11). DOTA gives oriented boxes (8 corner coords); we axis-align them.
#
# class map:
#   plane                          -> Aircraft-Fixed
#   helicopter                     -> Aircraft-Rotary
#   ship, harbor                   -> Watercraft
#   small-vehicle, large-vehicle   -> Vehicle-Wheeled
#   storage-tank, container-crane  -> Structure-Temp   (rough proxy)
#   everything else                -> dropped (background)
#
# usage:
#   python scripts/convert_dota.py \
#       --src  data/raw/DOTA \
#       --dst  data/processed/v0.1_dota_baseline \
#       --splits train val
from __future__ import annotations

import argparse
import shutil
import sys
from collections.abc import Iterable
from pathlib import Path

# DOTA name -> (our_class_id, our_name)  per docs/11
CLASS_MAP: dict[str, tuple[int, str]] = {
    "plane":           (4, "Aircraft-Fixed"),
    "helicopter":      (3, "Aircraft-Rotary"),
    "ship":            (5, "Watercraft"),
    "harbor":          (5, "Watercraft"),
    "small-vehicle":   (1, "Vehicle-Wheeled"),
    "large-vehicle":   (1, "Vehicle-Wheeled"),
    "storage-tank":    (6, "Structure-Temp"),
    "container-crane": (6, "Structure-Temp"),
}
# Person + tracked vehicles aren't in DOTA - come from VEDAI / xView / internal.
OUR_CLASS_NAMES = [
    "Person", "Vehicle-Wheeled", "Vehicle-Tracked",
    "Aircraft-Rotary", "Aircraft-Fixed", "Watercraft", "Structure-Temp",
]


def _try_pillow() -> bool:
    try:
        from PIL import Image  # noqa: F401
        return True
    except ImportError:
        return False


def _image_size(p: Path) -> tuple[int, int]:
    # (w, h) without loading pixels
    from PIL import Image
    with Image.open(p) as im:
        return im.size


def _obb_to_yolo(coords: list[float], iw: int, ih: int) -> tuple[float, float, float, float]:
    # axis-align an oriented box, return normalised (cx, cy, w, h)
    xs = coords[0::2]
    ys = coords[1::2]
    xmin = max(0.0, min(xs))
    xmax = min(float(iw), max(xs))
    ymin = max(0.0, min(ys))
    ymax = min(float(ih), max(ys))
    w = max(0.0, xmax - xmin)
    h = max(0.0, ymax - ymin)
    cx = xmin + w / 2.0
    cy = ymin + h / 2.0
    return cx / iw, cy / ih, w / iw, h / ih


def _convert_split(src_root: Path, dst_root: Path, split: str) -> tuple[int, int, int]:
    # returns (images_in, images_out, boxes_out)
    img_src = src_root / split / "images"
    lbl_src = src_root / split / "labelTxt"
    if not img_src.is_dir() or not lbl_src.is_dir():
        raise FileNotFoundError(f"Expected {img_src} and {lbl_src} to exist")

    img_dst = dst_root / "images" / split
    lbl_dst = dst_root / "labels" / split
    img_dst.mkdir(parents=True, exist_ok=True)
    lbl_dst.mkdir(parents=True, exist_ok=True)

    n_in = n_out = n_boxes = 0
    for img_path in sorted(img_src.iterdir()):
        if img_path.suffix.lower() not in {".png", ".jpg", ".jpeg", ".tif", ".tiff"}:
            continue
        n_in += 1
        lbl_path = lbl_src / f"{img_path.stem}.txt"
        if not lbl_path.exists():
            continue
        try:
            iw, ih = _image_size(img_path)
        except Exception as e:
            print(f"  ! skipping unreadable image {img_path.name}: {e}", file=sys.stderr)
            continue

        out_lines: list[str] = []
        with open(lbl_path, encoding="utf-8") as f:
            for raw in f:
                raw = raw.strip()
                if not raw or raw.startswith("imagesource") or raw.startswith("gsd"):
                    continue
                parts = raw.split()
                if len(parts) < 10:
                    continue
                coords = [float(x) for x in parts[:8]]
                dota_class = parts[8]
                mapped = CLASS_MAP.get(dota_class)
                if mapped is None:
                    continue
                cls_id, _ = mapped
                cx, cy, bw, bh = _obb_to_yolo(coords, iw, ih)
                # drop tiny boxes (doc 4 §5: >5x5 px after scaling)
                if bw * iw < 5 or bh * ih < 5:
                    continue
                out_lines.append(f"{cls_id} {cx:.6f} {cy:.6f} {bw:.6f} {bh:.6f}")

        if not out_lines:
            continue
        shutil.copy2(img_path, img_dst / img_path.name)
        (lbl_dst / f"{img_path.stem}.txt").write_text(
            "\n".join(out_lines) + "\n", encoding="utf-8")
        n_out += 1
        n_boxes += len(out_lines)
    return n_in, n_out, n_boxes


def _write_data_yaml(dst_root: Path, splits: Iterable[str]) -> Path:
    # ultralytics-compatible data.yaml
    splits = list(splits)
    lines = [
        "# Auto-generated by scripts/convert_dota.py",
        f"path: {dst_root.resolve()}",
        f"train: images/{'train' if 'train' in splits else splits[0]}",
        f"val:   images/{'val'   if 'val'   in splits else splits[-1]}",
    ]
    if "test" in splits:
        lines.append("test:  images/test")
    lines.append("")
    lines.append(f"nc: {len(OUR_CLASS_NAMES)}")
    lines.append("names:")
    for i, name in enumerate(OUR_CLASS_NAMES):
        lines.append(f"  {i}: {name}")
    out = dst_root / "data.yaml"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src",    type=Path, required=True, help="DOTA root with train/ val/ subdirs")
    ap.add_argument("--dst",    type=Path, required=True, help="output dataset root (versioned dir)")
    ap.add_argument("--splits", nargs="+", default=["train", "val"])
    args = ap.parse_args()

    if not _try_pillow():
        print("ERROR: Pillow is required (pip install pillow)", file=sys.stderr)
        return 2

    args.dst.mkdir(parents=True, exist_ok=True)
    totals = [0, 0, 0]
    for split in args.splits:
        print(f"[{split}] converting ...")
        a, b, c = _convert_split(args.src, args.dst, split)
        totals = [t + x for t, x in zip(totals, [a, b, c], strict=True)]
        print(f"[{split}] images_in={a}  images_out={b}  boxes_out={c}")

    yaml_path = _write_data_yaml(args.dst, args.splits)
    print(f"Wrote {yaml_path}")
    print(f"TOTAL images_in={totals[0]}  images_out={totals[1]}  boxes_out={totals[2]}")

    # repoint data/processed/current -> this version (training reads from there)
    current = args.dst.parent / "current"
    if current.is_symlink() or current.exists():
        try:
            current.unlink()
        except IsADirectoryError:
            shutil.rmtree(current)
    current.symlink_to(args.dst.resolve(), target_is_directory=True)
    print(f"Symlinked {current} -> {args.dst}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
